### PR TITLE
Reverts change to separate github actions - sets second job to only run after fetchy

### PR DESCRIPTION
**Pull request by andycarrell**

### CODE REVIEW

**Comment by theramis** [comment]
TBH I find this more confusing haha

**Comment by andycarrell** [comment]
@theramis pick your poison haha

Going to keep trying, to see if I can get it to work well. You can decide to merge or close, I think there's arguments for each!

**Comment by andycarrell** [comment]
@theramis - if we're querying when fetchy last ran, then wouldn't it be better to have these actions separate anyway?

**Comment by theramis** [comment]
> @theramis - if we're querying when fetchy last ran, then wouldn't it be better to have these actions separate anyway?

yup haha, It's easy enough to do it with one too but easier with them separate. 

TBH I prefer seperate than having one file

**Comment by andycarrell** [comment]
The more I think about it, I agree!

**Pull request closed without merging**
